import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import { Provider } from "@/components/ui/provider";
import { TodoProvider } from "./contexts/todoContext";

export const jakartaSans = Plus_Jakarta_Sans({
  variable: "--font-jakarta-sans",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
});

const metadata: Metadata = {
  title: "My Todod App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${jakartaSans.variable} `}>
        <Provider>
          <TodoProvider>{children}</TodoProvider>
        </Provider>
      </body>
    </html>
  );
}
